# Text shown on the index page.
index_title: Recettes de cuisine de Guillaume
index_description:
  Adresse ultra-secrète où sont entreposées mes recettes...

# Whether to show each recipe's image, if available, on the index page. To
# enable, set this option to any non-empty value (other than "false" in recent
# versions of Pandoc). To disable, keep it blank.
show_images_on_index:

# You can change the content language (really only relevant for hyphenation)
# and related textual labels here.
lang: fr
strings:
  search_placeholder: Recherche...
  uncategorized_label: Divers
  source_label: Source
  spicy_label: Epicé
  vegan_label: Vegan
  meat_label: Viande
  footer_text: N'hésitez pas à partager !
  updated_on: Dernière mise à jour le

